version: "3.9"

services:
  app:
    build: docker/php
    container_name: basic-app
    volumes:
      - ./:/app
    depends_on:
      - db

  nginx:
    build: docker/nginx
    container_name: basic-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: basic-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

