version: "3.9"

services:
  app:
    build: docker/php
    container_name: basic-app
    volumes:
      - ./:/app
    depends_on:
      - db

  nginx:
    build: docker/nginx
    container_name: basic-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: basic-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    container_name: basic-adminer
    ports:
      - 8080:8080
    depends_on:
      - db