version: "3.9"

services:
  app:
    build: docker/php
    container_name: basic-app
    volumes:
      - ./:/app
    depends_on:
      - db

  nginx:
    build: docker/nginx
    container_name: basic-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: basic-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: '/var/lib/postgresql/data/pgdata' # Critical for Postgres to work in the container
#    volumes:
#      - .:/var/lib/postgresql/data

  db-second:
    image: mysql:8.0
    container_name: basic-db-second
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

  adminer:
    image: adminer
    container_name: basic-adminer
    depends_on:
      - db
    ports:
      - 8080:8080

