name: CI

on: [push]

env:
  DEPLOY_PATH: ${{ secrets.PROJECT_PATH }}
  BUILD_SCRIPT_OUTPUT: .
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Доставляем собранное приложение на сервер
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}, !${{ env.BUILD_SCRIPT_OUTPUT }}/runtime, ${{ env.BUILD_SCRIPT_OUTPUT }}/.git
          target: /${{ env.DEPLOY_PATH }}
          strip_components: 1
      - name: Print Info
        run: echo "Deployed at hosting/"